### ISSUE TITLE
wrongly applies font on non-Windows

### ISSUE THREAD

**Issue by Alexey-T** [veksha/cuda_font_changer#4]
after choosing a font, I got in user.json
```
  "font_name__linux" : "DejaVu Sans Mono", ///////// this is OLD choice
  "font_size__linux" : 9,
    "font_name": "KacstDecorative", /////this is my choice in plugin!! no suffix!!
```

**Comment by Alexey-T** [comment]
PROC_GET_OS_SUFFIX: Returns string of OS suffix, which is used in some CudaText option names. Possible values are listed in the default.json file. @veksha

**Comment by veksha** [comment]
very very nice!
